### ISSUE TITLE
My site is stopped working i am using blank slate theme.

### ISSUE THREAD

**Issue by rahulbisen007** [bhadaway/blankslate#59]
I am attaching my current site issues. Please help me to resolve these.

I am getting below error 

**Call to undefined function wp_body_open() in D:\home\crestadentalimplants.com\wwwroot\wp-content\themes\blankslate\header.php on line 9.**

then i added a check function in header.php page.

function_exists( 'wp_body_open' ) ) {
    wp_body_open();
}

now my site is not throwing above error but listing with proper CSS.

![Screenshot from 2024-05-16 10-52-57](https://github.com/bhadaway/blankslate/assets/59677342/219f875f-d8ad-4ede-8a63-34eef7885bad)

**Comment by bhadaway** [comment]
Basically, what happened is you removed something from the default templates that caused an error. When that happens, you'll want to reference the vanilla templates again to see how to put Humpty Dumpty back together.

For the original context and code for this specific issue, see:

https://github.com/bhadaway/blankslate/blob/master/functions.php#L98

and

https://github.com/bhadaway/blankslate/blob/master/header.php#L9

**Comment by rahulbisen007** [comment]
I restored original code what you suggested but still my siste is looking
like same as previously attached screen shot.

Please help me to solve this issue.

Thanks

**Comment by bhadaway** [comment]
> then i added a check function in header.php page.
> 
> function_exists( 'wp_body_open' ) ) {
> wp_body_open();
> }

This is incorrect.

Review https://github.com/bhadaway/blankslate/blob/master/functions.php#L98 and https://github.com/bhadaway/blankslate/blob/master/header.php#L9 again.
